### ISSUE TITLE
ConcurrentModificationException accessing discovered results

### ISSUE THREAD

**Issue by farble1670** [devgianlu/zeroconf-java#20]
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1089)
	at com.clover.nsd_stress.ZeroconfStressActivity.discover$lambda-5(ZeroconfStressActivity.kt:159)
```

I see the backing `services` field is a synchronized set, but according to the docs:
> It is imperative that the user manually synchronize on the returned set when iterating over it.

However when the field is returned, it's wrapped in a `Collections.unmodifiableCollection` which just restricts write but not read operations on the wrapped collection. The caller has no idea they need to synchronize because they have no idea the result is a wrapped `SynchronizedSet`.

One option would be to have the `getService()` method synchronize on the source collection, making a copy, then return the copy. Or you could back it with a `java.util.concurrent` collection implementation.

**Comment by farble1670** [comment]
Here's a good SO post that talks about this. 
https://stackoverflow.com/questions/23450227/is-iteration-via-collections-synchronizedset-foreach-guaranteed-to-be-thr/

I happen to be using Kotlin, like this:
```
discoveredServices.services.forEach { ...
```
which is not using `Set.forEach` but it rather some syntactic sugar over the iterator.

**Comment by devgianlu** [comment]
Are you able to make a PR? I can merge it right now, but can't do it myself.

**Comment by farble1670** [comment]
Sure, let me stress test it a bit. Thanks for your quick response.

**Comment by saket** [comment]
Is this related to https://github.com/devgianlu/zeroconf-java/issues/17?
