### ISSUE TITLE
Zeroconf:807 - Failed receiving/sending packet!

### ISSUE THREAD

**Issue by AlexanderBabel** [devgianlu/zeroconf-java#39]
Hey there,

this package is used in [librespot-java](https://github.com/librespot-org/librespot-java) and I am facing heavy log spam right now with the following error message:

```
2022-11-10 11:19:35,117 WARN  Zeroconf:807 - Failed receiving/sending packet!
java.lang.IllegalArgumentException: newPosition > limit: (1345 > 345)
	at java.nio.Buffer.createPositionException(Buffer.java:318) ~[?:?]
	at java.nio.Buffer.position(Buffer.java:293) ~[?:?]
	at java.nio.ByteBuffer.position(ByteBuffer.java:1094) ~[?:?]
	at java.nio.ByteBuffer.position(ByteBuffer.java:262) ~[?:?]
	at xyz.gianlu.zeroconf.Record.readName(Record.java:57) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.RecordSRV.readData(RecordSRV.java:29) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Record.readAnswer(Record.java:78) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Packet.read(Packet.java:93) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Zeroconf$ListenerThread.run(Zeroconf.java:798) [librespot-java.jar:1.6.2]
2022-11-10 11:19:36,158 WARN  Zeroconf:807 - Failed receiving/sending packet!
java.lang.IllegalArgumentException: newPosition > limit: (1345 > 191)
	at java.nio.Buffer.createPositionException(Buffer.java:318) ~[?:?]
	at java.nio.Buffer.position(Buffer.java:293) ~[?:?]
	at java.nio.ByteBuffer.position(ByteBuffer.java:1094) ~[?:?]
	at java.nio.ByteBuffer.position(ByteBuffer.java:262) ~[?:?]
	at xyz.gianlu.zeroconf.Record.readName(Record.java:57) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.RecordSRV.readData(RecordSRV.java:29) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Record.readAnswer(Record.java:78) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Packet.read(Packet.java:97) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.zeroconf.Zeroconf$ListenerThread.run(Zeroconf.java:798) [librespot-java.jar:1.6.2]
```

It is worth mentioning that the number on the right of the greater-than sign is changing its value.

Used version: 1.3.2

**Comment by devgianlu** [comment]
It looks like it doesn't like the DNS packets it's receiving. Not sure why honestly.
