### ISSUE TITLE
addAllNetworkInterfaces -> Only IPv6 sockets can join IPv6 multicast group

### ISSUE THREAD

**Issue by Erhannis** [devgianlu/zeroconf-java#6]
My program works on this Linux computer and this Windows computer, but not this Mac computer.  Not sure if it's the OS or if it's just something to do with its interfaces.  I get the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Only IPv6 sockets can join IPv6 multicast group
	at sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:811)
	at sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:894)
	at xyz.gianlu.zeroconf.Zeroconf$ListenerThread.addNetworkInterface(Zeroconf.java:586)
	at xyz.gianlu.zeroconf.Zeroconf.addNetworkInterface(Zeroconf.java:188)
	at xyz.gianlu.zeroconf.Zeroconf.addAllNetworkInterfaces(Zeroconf.java:227)
	at com.erhannis.lancopy.JmDNSProcess.<init>(JmDNSProcess.java:128)
	at com.erhannis.lancopy.JmDNSProcess.start(JmDNSProcess.java:158)
	at com.erhannis.lancopy.Frame.main(Frame.java:588)
	at com.erhannis.lancopy.Main.main(Main.java:49)
```

The relevant code is:

```java
zeroconf0 = new Zeroconf();
zeroconf0.addAllNetworkInterfaces()
         .setUseIpv4(true)
         .setUseIpv6(false);
```
as I believe I saw in the example file.

**Comment by devgianlu** [comment]
Should be fixed like this: 

```java
zeroconf0 = new Zeroconf();
zeroconf0.setUseIpv4(true)
    .setUseIpv6(false);
    .addAllNetworkInterfaces()
```
